// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Advisory character and token profile for a repeated artefact candidate.
 */
export type CandidateTextProfile = { char_count: number, token_count: number, alphabetic_ratio: number, digit_ratio: number, symbol_ratio: number, whitespace_ratio: number, uppercase_ratio: number, average_token_length: number, max_repeated_char_run: number, suspicious_token_ratio: number, has_sentence_punctuation: boolean, looks_like_common_section_heading: boolean, looks_like_page_label: boolean, looks_like_table_or_numeric_row: boolean, looks_like_formula_or_code: boolean, looks_like_markup_or_extraction_noise: boolean, };
