// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Advisory text/noise label for candidate review.
 */
export type CandidateTextSignalLabel = "likely_natural_text" | "likely_section_heading" | "likely_page_label" | "likely_table_or_numeric_row" | "likely_formula_or_code" | "likely_markup_or_extraction_noise" | "ambiguous";
