// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilePreview } from "./FilePreview";
import type { PreviewWarning } from "./PreviewWarning";

export type CombinedPreview = { files: Array<FilePreview>, combined_text: string, total_files_previewed: number, total_characters_included: number, warnings: Array<PreviewWarning>, };
