// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportWarningKind = "invalid_utf8" | "extraction_warning" | "extraction_error";
