// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportWarningKind } from "./ExportWarningKind";

export type ExportWarning = { source_path: string | null, output_path: string | null, kind: ExportWarningKind, message: string, };
