// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleaningConfig } from "./CleaningConfig";
import type { ManifestFileRecord } from "./ManifestFileRecord";

export type ExportManifest = { app_name: string, app_version: string | null, export_timestamp: string, files_exported: number, warnings_count: number, cleaning_config: CleaningConfig, files: Array<ManifestFileRecord>, };
