// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PdfAuditSuggestedProfile = "standard" | "layout_heavy" | "ocr_rescue" | "force_ocr";
