// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PdfAuditQuality } from "./PdfAuditQuality";
import type { PdfAuditSuggestedProfile } from "./PdfAuditSuggestedProfile";

export type PdfAuditResult = { path: string, file_name: string, page_count: number | null, sampled_page_count: number, embedded_text_detected: boolean, embedded_text_chars: number, quality: PdfAuditQuality, pdfium_available: boolean, ocr_model_resources_available: boolean, ocr_full_usability_checked: boolean, degraded_fallback_used: boolean, suggested_profile: PdfAuditSuggestedProfile, warnings: Array<string>, };
