// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PdfPageExtractionMethod } from "./PdfPageExtractionMethod";

export type PdfPageRangePage = { page_index: number, page_number: number, text: string, char_count: number, method: PdfPageExtractionMethod, warnings: Array<string>, render_clamped: boolean, error: string | null, };
