// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PdfPageRangePage } from "./PdfPageRangePage";

export type PdfPageRangeResult = { page_count: number, start_page_index: number, end_page_index: number, pages: Array<PdfPageRangePage>, warnings: Array<string>, };
