// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of candidate occurrences by estimated layout positions.
 */
export type PositionSummary = { top_count: number, middle_count: number, bottom_count: number, unknown_count: number, };
