// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewWarningKind } from "./PreviewWarningKind";

export type PreviewWarning = { source_path: string | null, relative_path: string | null, kind: PreviewWarningKind, message: string, };
