// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text area affected by a structured removal rule.
 */
export type RemovalScope = "anywhere" | "whole_line" | "page_top" | "page_bottom" | "page_top_or_bottom";
