// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Matcher used by a structured removal rule.
 */
export type RemovalMatcher = { "kind": "literal", text: string, } | { "kind": "normalized_line", normalized_key: string, };
