// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemovalMatcher } from "./RemovalMatcher";
import type { RemovalRuleSource } from "./RemovalRuleSource";
import type { RemovalScope } from "./RemovalScope";

/**
 * Structured removal rule applied during text cleaning.
 */
export type RemovalRule = { id: string, label: string, source: RemovalRuleSource, matcher: RemovalMatcher, scope: RemovalScope, enabled: boolean, };
