// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin of a structured removal rule.
 */
export type RemovalRuleSource = "manual" | "promoted_repeated_artifact" | "generated_pdf_cleanup";
