// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The types of candidates that can be detected.
 */
export type RepeatedArtifactKind = "exact_line" | "normalized_line" | "two_line_block" | "three_line_block" | "inline_artifact";
