// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single search hit with ready-to-render context strings.
 *
 * All text fields are char-boundary-safe slices of the original extracted text.
 * The frontend should use these strings directly, not try to compute offsets.
 */
export type SearchHit = { 
/**
 * Index into the corpus records array.
 */
corpus_index: number, 
/**
 * Relative path of the containing file.
 */
relative_path: string, 
/**
 * Full source path, if available.
 */
source_path: string | null, 
/**
 * Up to ~CONTEXT_CHARS chars of text before the match.
 */
context_before: string, 
/**
 * The exact matched substring.
 */
match_text: string, 
/**
 * Up to ~CONTEXT_CHARS chars of text after the match.
 */
context_after: string, 
/**
 * 0-based index of this match within its file.
 */
file_match_index: number, };
