// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk labels that are advisory reviews rather than absolute truths.
 */
export type ArtifactRiskLabel = "strong_header_footer_candidate" | "possible_boilerplate" | "common_section_heading_review_carefully" | "symbol_or_noise_candidate" | "ambiguous";
