// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content-class label for a candidate, based on character composition.
 * Used to filter candidates and warn users about risky groupings.
 */
export type CandidateContentClass = "text_dominant" | "mixed_text_numbers" | "numeric_dominant" | "symbol_noise_dominant";
