// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentTypeCounts } from "./DocumentTypeCounts";

export type CorpusSummary = { root: string, files_discovered: number, files_supported: number, files_ignored: number, total_size_bytes: number, document_type_counts: DocumentTypeCounts, };
