// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentTypeCounts = { text: number, html: number, docx: number, pdf: number, };
