// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentType } from "./DocumentType";

export type DocumentRecord = { source_path: string, relative_path: string, document_type: DocumentType, size_bytes: number, };
