// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportManifest } from "./ExportManifest";
import type { ExportWarning } from "./ExportWarning";
import type { ManifestFileRecord } from "./ManifestFileRecord";

export type ExportReport = { output_dir: string, texts_dir: string, manifest_path: string, warnings_path: string, config_path: string, readme_path: string, files_exported: number, warnings_count: number, exported_files: Array<ManifestFileRecord>, warnings: Array<ExportWarning>, manifest: ExportManifest, };
