// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentType } from "./DocumentType";
import type { PreviewWarning } from "./PreviewWarning";

export type FilePreview = { source_path: string, relative_path: string, document_type: DocumentType, text: string, source_size_bytes: number, included_char_count: number, truncated: boolean, warnings: Array<PreviewWarning>, };
