// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A specific example instance of a repeated candidate.
 */
export type RepeatedArtifactExample = { file_name: string, file_path: string, line_number: number | null, page_number: number | null, context_before: string | null, matched_text: string, context_after: string | null, };
