// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepeatedArtifactCandidate } from "./RepeatedArtifactCandidate";
import type { RepeatedArtifactScanDiagnostics } from "./RepeatedArtifactScanDiagnostics";

/**
 * Scan report containing both candidates and diagnostics.
 */
export type RepeatedArtifactScanReport = { candidates: Array<RepeatedArtifactCandidate>, diagnostics: RepeatedArtifactScanDiagnostics, };
