// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusSummary } from "./CorpusSummary";
import type { DocumentRecord } from "./DocumentRecord";

export type ScanReport = { root: string, files: Array<DocumentRecord>, files_discovered: number, files_supported: number, files_ignored: number, total_size_bytes: number, summary: CorpusSummary, };
